Added horizontal rule and task checkboxes
MeanderingProgrammer/markdown.nvim pull request #13
Opened 2024-04-07 10:03 UTC by shabaev

- Added [headlines.nvim](https://github.com/lukas-reineke/headlines.nvim) behave of horizontal rules;
- Improved (commit)[https://github.com/JockeKv/markdown.nvim/commit/5fbcc4efdbbcc418c99a7e0ab654a90d5f7b2546] to be used in the plugin;
- Fixed tree-sitter query for the quotes.
```
> here is the first line
> here is the second line
>
> > here is the first line
> > here is the second line

> - [x] tasks#1
> > - [x] task#1.1
> > - [ ] task#1.2
```

2024-04-11 23:05 UTC, MeanderingProgrammer requested changes

2024-04-11 23:05 UTC, MeanderingProgrammer commented on README.md
> +        (block_continuation) @quote_marker
While I get what you're going for here `block_continuation` types are used far too much to match on them as a quote marker: https://github.com/tree-sitter-grammars/tree-sitter-markdown/blob/split_parser/tree-sitter-markdown/src/grammar.json

As the name implies they are the continuation of any block, including list items, code fences, etc.

This works because the logic only updates `>` symbols but it confuses me too much. Things selected in a group should be that thing. A `quote_marker` is always a quote marker, a `list_marker` is always a list marker. 

Though I understand that this does not handle nested quotes particularly well.

2024-04-11 23:05 UTC, MeanderingProgrammer commented on README.md
> +        (thematic_break) @dash
Thematic break change looks good.

2024-04-11 23:05 UTC, MeanderingProgrammer commented on lua/render-markdown/handler/markdown.lua
> +        elseif capture == 'checkbox' then
I'm on the fence with the whole checkbox change.

Rather than relying on some internal logic to get information about whether this is a checked or unchecked box can you separate these into 2 different groups. Something like `unchecked_box` and `checked_box`. The way pipe_tables are handled is a decent reference for what I'm thinking.

Similarly rather than having a list of values for checkboxes can you nest it into:

```lua
checkbox = {
  unchecked = 'some_value',
  checked = 'some_value',
}
```

The nested nature of lists and headings is what led to the cyclical patterns, with checkboxes there are only 2 states so we can be more explicit.

2024-04-11 23:22 UTC, MeanderingProgrammer commented on README.md
> +        (thematic_break) @dash
Merged the horizontal break change in: https://github.com/MeanderingProgrammer/markdown.nvim/commit/af819f39c63aeb09ff3801dbfd5188cea55e48e7

2024-04-13 17:35 UTC, shabaev commented on lua/render-markdown/handler/markdown.lua
> +        elseif capture == 'checkbox' then
no problem. done/checked - https://github.com/MeanderingProgrammer/markdown.nvim/pull/13/commits/9cca5b34fbf3fc366e81eed462f7368fd17bfbbe

2024-04-13 17:44 UTC, shabaev commented on README.md
> +        (block_continuation) @quote_marker
Right you are. I typed `block_continuation` and meant kinda `block_quote_continuation`. Reverted the commit.
> Though I understand that this does not handle nested quotes particularly well.

Yup. Thanks.

2024-04-14 04:37 UTC, MeanderingProgrammer commented
Thanks for putting this together!

I went ahead and merged the checkbox logic in this commit: https://github.com/MeanderingProgrammer/markdown.nvim/commit/90637a1120de47a3be57b00b7db4eee0d24834c8, largely copied from this PR.

Sorry to not just merge this PR as is, looks like you were in the process of making the final changes.

There were some modifications I made that I'll call out here:

* Everything in the `state.lua` Config class should be mandatory, the UserConfig makes everything optional but the actual Config should have a reasonable default for everything, including sub classes. This was probably just a copy pasta thing that left in the `?` in a few places.
* I wasn't sure why the task_list_marker_unchecked / task_list_marker_checked tree sitter queries included the list_marker_* prefix so I removed them and simplified those to the minimum. LMK if you had a reason for adding them. The reason to do this for the list_marker query was to avoid changing ordered lists, but since here we're updating the checkboxes, this isn't necessary.
* I removed the `(paragraph)` addition to the list_marker query, was also unsure about the reason for that, LMK if there was one.
* Slight change to how the condition for checkbox_unchecked & checkbox_checked is handled in `ui.lua` to reduce some of the duplication and handle different padding / character widths.

Some of these I might make more general and add to a contributing guide if there are more contributions, but I think it's getting to a fairly stable point.

Most are just my nit picky preferences.

I'll close out this PR since all the proposed changes are merged.

Feel free to shoot me any ideas or create more PRs more than happy to look over them.

Thanks again!

2024-04-14 04:39 UTC, closed without merging

2024-04-14 06:39 UTC, shabaev commented
gday,

> Sorry to not just merge this PR as is, looks like you were in the process of making the final changes.

nvm, it was a workable draft I were able and wanted to share with you to discuss and to pick some code. the goal achieved. thank you.

> Everything in the state.lua Config class should be mandatory,

yup. I overlooked that. thanks for watching my back :100: 

> included the list_marker_* prefix

the idea was to remove list bullets if it's a task list, but I agree with your point of view.

> to reduce some of the duplication

it looks perfect. thank you for the optimization (and to show me personally how to) :+1: